### ISSUE TITLE
predict 报错

### ISSUE THREAD

**Issue by Xuanfang1121** [taishan1994/pytorch_bert_bilstm_crf_ner#1]
在predict的时候报错，
Traceback (most recent call last):
  File "main.py", line 229, in <module>
    bertForNer.predict(raw_text, model_path)
  File "main.py", line 159, in predict
    token_type_ids, None)
  File "/torchgpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pytorch_bert_bilstm_crf_ner/bert_ner_model.py", line 84, in forward
    logits = self.crf.decode(seq_out, mask=attention_masks)
  File "torchgpu/lib/python3.6/site-packages/torchcrf/__init__.py", line 139, in decode
    return self._viterbi_decode(emissions, mask)
  File "/torchgpu/lib/python3.6/site-packages/torchcrf/__init__.py", line 305, in _viterbi_decode
    score = torch.where(mask[i].unsqueeze(1), next_score, score)
RuntimeError: Expected condition to have ScalarType Byte, but got ScalarType Long

这个怎么解决

**Comment by Xuanfang1121** [comment]
解决了，predict的时候attention mask tensor的类型转为unit8
