### ISSUE TITLE
大佬您好，使用您的cner任务，使用的是最初始的参数，use crf打开后，训练89轮报错，无法进行eval和保存模型

### ISSUE THREAD

**Issue by QMSLWSJ** [taishan1994/pytorch_bert_bilstm_crf_ner#36]
![Uploading T)}FO{(L]COZ)9Y8CBNW]3G.png…]()

**Comment by QMSLWSJ** [comment]
错误如下：
【train】 epoch:0 85/1434 loss:7.5998
【train】 epoch:0 86/1434 loss:12.1990
【train】 epoch:0 87/1434 loss:18.4305
【train】 epoch:0 88/1434 loss:13.8174
【train】 epoch:0 89/1434 loss:16.8664
Traceback (most recent call last):
  File "C:\Users\秋明山老王司机\Desktop\pytorch_bert_bilstm_crf_ner-main\main.py", line 266, in <module>
    bertForNer.train()
  File "C:\Users\秋明山老王司机\Desktop\pytorch_bert_bilstm_crf_ner-main\main.py", line 64, in train
    dev_loss, precision, recall, f1_score = self.dev()
  File "C:\Users\秋明山老王司机\Desktop\pytorch_bert_bilstm_crf_ner-main\main.py", line 83, in dev
    batch_output = np.array(batch_output)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (8,) + inhomogeneous part.

**Comment by taishan1994** [comment]
> 紧急求助，谢谢大佬

![image](https://user-images.githubusercontent.com/27845149/223405958-1b861b6c-1df1-48a8-9e8f-f0d18cf488da.png)

我直接拷贝项目运行的，没啥问题呀。

**Comment by taishan1994** [comment]
> 紧急求助，谢谢大佬

![image](https://user-images.githubusercontent.com/27845149/223405958-1b861b6c-1df1-48a8-9e8f-f0d18cf488da.png)

我直接拷贝项目运行的，没啥问题呀。

**Comment by taishan1994** [comment]
> setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (8,)

pytorch-crf版本是0.7.2么，再打印一下dev里面的batch_output，看看是什么。

**Comment by QMSLWSJ** [comment]
> 输出如下

![FVW71P2~YWWAZ{FMGHS~PYO](https://user-images.githubusercontent.com/127195326/223905871-5ee9e3b0-b2b3-4acf-9085-1e11828c5b0a.png)

**Comment by QMSLWSJ** [comment]
大佬，您能看看batch out有什么问题吗，或者您受累发一份您跑的源码看看吗，我是刚刚入门的纯小白，最近陷入瓶颈了，万分感谢！

**Comment by taishan1994** [comment]
> 大佬，您能看看batch out有什么问题吗，或者您受累发一份您跑的源码看看吗，我是刚刚入门的纯小白，最近陷入瓶颈了，万分感谢！

你这里面的每一条数据的长度都不一样，肯定是有问题的。运行的时候在命令行运行，pycharm里面的话要带参数运行。

**Comment by QMSLWSJ** [comment]
大佬，严格安装您的环境要求重试了一遍，跑通了，之前使用的是高版本pytorch和transformers，出现了这个问题，应该就是环境不兼容的问题，感谢大佬！

**Comment by QMSLWSJ** [comment]
前辈我在训练环节没有问题了，但是在predict预测部分，我将raw_txt修改为我的数据集，报错Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)。debug好像是Tensor数据类型的问题，但对于如何修改没有思路，请问您有什么好的见解吗？

**Comment by taishan1994** [comment]
> 前辈我在训练环节没有问题了，但是在predict预测部分，我将raw_txt修改为我的数据集，报错Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)。debug好像是Tensor数据类型的问题，但对于如何修改没有思路，请问您有什么好的见解吗？

predict里面改一下：
```attention_masks = torch.from_numpy(np.array(encode_dict['attention_mask'])).long().unsqueeze(0).to(device)```

**Comment by yjj-ui** [comment]
> 大佬，严格安装您的环境要求重试了一遍，跑通了，之前使用的是高版本pytorch和transformers，出现了这个问题，应该就是环境不兼容的问题，感谢大佬！

您好，请问您都调整了什么版本可以说一下吗
