### ISSUE TITLE
原始数据训练模型时遇到的问题

### ISSUE THREAD

**Issue by NLPnew** [taishan1994/pytorch_bert_bilstm_crf_ner#5]
用项目数据训练模型
     main.py中的部分代码：

            bertForNer = BertForNer(args, train_loader, dev_loader, test_loader, id2query)
            bertForNer.train()

            model_path = './checkpoints/{}/model.pt'.format(model_name)
            bertForNer.test(model_path)
1、遇到问题
Traceback (most recent call last):
  File "F:/pytorch_bert_bilstm_crf_ner-main/pytorch_bert_bilstm_crf_ner-main/main.py", line 252, in <module>
    bertForNer = BertForNer(args, train_loader, dev_loader, test_loader, id2query)
  File "F:/pytorch_bert_bilstm_crf_ner-main/pytorch_bert_bilstm_crf_ner-main/main.py", line 28, in __init__
    model = bert_ner_model.BertNerModel(args)
  File "F:\pytorch_bert_bilstm_crf_ner-main\pytorch_bert_bilstm_crf_ner-main\bert_ner_model.py", line 49, in __init__
    self.crf = CRF(args.num_tags,batch_first=True)
TypeError: __init__() got an unexpected keyword argument 'batch_first'
将batch_first=True去掉，可以运行，但是遇到了问题2

2.Traceback (most recent call last):
  File "F:/pytorch_bert_bilstm_crf_ner-main/pytorch_bert_bilstm_crf_ner-main/main.py", line 253, in <module>
    bertForNer.train()
  File "F:/pytorch_bert_bilstm_crf_ner-main/pytorch_bert_bilstm_crf_ner-main/main.py", line 45, in train
    loss, logits = self.model(batch_data['token_ids'], batch_data['attention_masks'], batch_data['token_type_ids'], batch_data['labels'])
  File "D:\python\Scripts\ve\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\pytorch_bert_bilstm_crf_ner-main\pytorch_bert_bilstm_crf_ner-main\bert_ner_model.py", line 76, in forward
    seq_out = seq_out.contiguous().view(batch_size, self.args.max_seq_len,-1) #[batchsize, max_len, num_tags]
RuntimeError: shape '[32, 256, -1]' is invalid for input of size 158400
不知道问题在哪里？

**Comment by NLPnew** [comment]
另外，方便加qq，说明问题吗？我的 983695424

**Comment by NLPnew** [comment]
上面的问题，是在训练bert_lstm_crf时遇到的，单独选择bert，会遇到下面问题
Traceback (most recent call last):
  File "F:/pytorch_bert_bilstm_crf_ner-main/pytorch_bert_bilstm_crf_ner-main/main.py", line 253, in <module>
    bertForNer.train()
  File "F:/pytorch_bert_bilstm_crf_ner-main/pytorch_bert_bilstm_crf_ner-main/main.py", line 49, in train
    loss.backward()
  File "D:\python\Scripts\ve\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\python\Scripts\ve\lib\site-packages\torch\autograd\__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
也是不明白啥情况

**Comment by taishan1994** [comment]
> 另外，方便加qq，说明问题吗？我的 983695424

加我微信：15926459981
