### ISSUE TITLE
Albert问题

### ISSUE THREAD

**Issue by wenling19** [taishan1994/pytorch_bert_bilstm_crf_ner#51]
请问模型换成Albert后，会出现下面的错误是什么原因啊？
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    bertForNer = BertForNer(args, train_loader, dev_loader, test_loader, id2query)
  File "main.py", line 31, in __init__
    model = bert_ner_model.BertNerModel(args)
  File "/root/autodl-tmp/bert/bert_ner_model.py", line 12, in __init__
    super(BertNerModel, self).__init__(bert_dir=args.bert_dir, dropout_prob=args.dropout_prob)
  File "/root/autodl-tmp/bert/bert_base_model.py", line 18, in __init__
    self.bert_module = BertModel.from_pretrained(bert_dir, output_hidden_states=True,
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 975, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 403, in from_pretrained
    assert (
AssertionError: You tried to initiate a model of type 'bert' with a pretrained model of type 'albert'

**Comment by taishan1994** [comment]
> 请问模型换成Albert后，会出现下面的错误是什么原因啊？ Traceback (most recent call last): File "main.py", line 232, in bertForNer = BertForNer(args, train_loader, dev_loader, test_loader, id2query) File "main.py", line 31, in **init** model = bert_ner_model.BertNerModel(args)

可能不能使用BertModel来初始化模型，可以看看它是怎么加载的，比如是不是使用AutoModel。

**Comment by taishan1994** [comment]
> 请问模型换成Albert后，会出现下面的错误是什么原因啊？ Traceback (most recent call last): File "main.py", line 232, in bertForNer = BertForNer(args, train_loader, dev_loader, test_loader, id2query) File "main.py", line 31, in **init** model = bert_ner_model.BertNerModel(args)

可能不能使用BertModel来初始化模型，可以看看它是怎么加载的，比如是不是使用AutoModel。
