### ISSUE TITLE
求助作者老师:在使用Bert和Bert-idnn-crf两个模型时会报如下错误：找不到model.pt。但是同样的参数Bert-crf和 bert-listm-crf则不会

### ISSUE THREAD

**Issue by LiYiFeng0706** [taishan1994/pytorch_bert_bilstm_crf_ner#57]
Traceback (most recent call last):
  File "main.py", line 281, in <module>
    bertForNer.test(model_path, test_callback_info)
  File "main.py", line 123, in test
    model, device = trainUtils.load_model_and_parallel(model, self.args.gpu_ids, model_path)
  File "E:\常用文件\硕士_毕业论文相关\pycharm项目\utils\trainUtils.py", line 98, in load_model_and_parallel
    state_dict = torch.load(ckpt_path, map_location=torch.device('cpu'))
  File "D:\Anconda\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Anconda\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Anconda\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/bert_cner/model.pt'

**Comment by taishan1994** [comment]
要先训练才会有model.pt
